export const SET_USER = 'SET_USER'
export const SET_SETTINGS = 'SET_SETTINGS'

export const REQUEST_QUIZ = 'REQUEST_QUIZ'
export const RECEIVE_QUIZ = 'RECEIVE_QUIZ'
export const START_QUIZ = 'START_QUIZ'
export const CANCEL_QUIZ = 'CANCEL_QUIZ'

export const PROGRESS_QUESTION = 'PROGRESS_QUESTION'
export const ADD_ANSWER = 'ADD_ANSWER'
export const FINISH_QUIZ = 'FINISH_QUIZ'

export const REVIEW_QUIZ = 'REVIEW_QUIZ'

export const QUESTION_ENTITIES_UPDATE = 'QUESTION_ENTITIES_UPDATE'
export const ANSWER_ENTITIES_UPDATE = 'ANSWER_ENTITIES_UPDATE'

export const RECEIVE_IS_AUTHENTICATED = 'RECEIVE_IS_AUTHENTICATED'
export const RECEIVE_AUTH_ERROR = 'RECEIVE_AUTH_ERROR'